// Transport between GhosttyTerminal.tsx and the Go PtyService (see
// apps/desktop/CONTRACT.md, "Go: services and events"). Falls back to a no-op,
// input-echoing transport when not running under Wails (e.g. `bun run dev` in a
// plain browser), the same pattern src/native.ts uses for its own bindings.

import { isWails as inWails } from "../lib/wails.ts";

async function ptyService() {
  try {
    // @ts-ignore — generated by `wails3 generate bindings`; may not exist at typecheck/build time.
    return await import("../../bindings/portfolio-desktop/ptyservice.ts");
  } catch {
    return null;
  }
}

async function events() {
  try {
    return await import("@wailsio/runtime");
  } catch {
    return null;
  }
}

export interface PtyCreateOptions {
  cwd?: string;
  cols: number;
  rows: number;
  command?: string;
}

/** One session's transport: write/resize/close plus its own data/exit subscriptions. */
export interface PtySession {
  readonly id: string;
  write(data: string): void;
  resize(cols: number, rows: number): void;
  close(): void;
  onData(listener: (text: string) => void): () => void;
  onExit(listener: (code: number) => void): () => void;
  dispose(): void;
}

interface PtyDataEventPayload { Id: string; Data: string }
interface PtyExitEventPayload { Id: string; Code: number }

// One Events.On("pty:data" | "pty:exit") subscription for the whole app, fanned out to
// per-session listeners by id, so each PtySession does not register its own global handler.
let dataListeners: Map<string, Set<(text: string) => void>> | null = null;
let exitListeners: Map<string, Set<(code: number) => void>> | null = null;
let decoders: Map<string, TextDecoder> | null = null;
let subscribed = false;

function base64ToBytes(base64: string): Uint8Array {
  const binary = atob(base64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
  return bytes;
}

async function ensureSubscribed(): Promise<void> {
  if (subscribed) return;
  subscribed = true;
  dataListeners = new Map();
  exitListeners = new Map();
  decoders = new Map();

  const runtime = await events();
  if (!runtime) return;
  const { Events } = runtime as typeof import("@wailsio/runtime");

  Events.On("pty:data", (event: { data: PtyDataEventPayload }) => {
    const { Id, Data } = event.data;
    const listeners = dataListeners?.get(Id);
    if (!listeners || listeners.size === 0) return;
    let decoder = decoders?.get(Id);
    if (!decoder) {
      decoder = new TextDecoder("utf-8");
      decoders?.set(Id, decoder);
    }
    const text = decoder.decode(base64ToBytes(Data), { stream: true });
    listeners.forEach(listener => listener(text));
  });

  Events.On("pty:exit", (event: { data: PtyExitEventPayload }) => {
    const { Id, Code } = event.data;
    exitListeners?.get(Id)?.forEach(listener => listener(Code));
  });
}

function subscribe<K>(map: Map<string, Set<K>>, id: string, listener: K): () => void {
  let set = map.get(id);
  if (!set) {
    set = new Set();
    map.set(id, set);
  }
  set.add(listener);
  return () => {
    set?.delete(listener);
    if (set?.size === 0) map.delete(id);
  };
}

/** Creates a pty session (or a browser-only fallback) and returns its transport handle. */
export async function createPtySession(options: PtyCreateOptions): Promise<PtySession> {
  await ensureSubscribed();

  if (inWails()) {
    const service = await ptyService();
    if (service) {
      const id = await service.Create({
        Cwd: options.cwd ?? "",
        Cols: options.cols,
        Rows: options.rows,
        Command: options.command ?? "",
      });
      return {
        id,
        write: (data: string) => { void service.Write(id, data); },
        resize: (cols: number, rows: number) => { void service.Resize(id, cols, rows); },
        close: () => { void service.Close(id); },
        onData: listener => subscribe(dataListeners!, id, listener),
        onExit: listener => subscribe(exitListeners!, id, listener),
        dispose: () => { decoders?.delete(id); },
      };
    }
  }

  return createFallbackSession(options);
}

// Not running under Wails: no real shell exists, so typed input is echoed back so the
// component still renders and behaves like a terminal in a plain browser tab.
function createFallbackSession(options: PtyCreateOptions): PtySession {
  const id = `fallback-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 8)}`;
  const dataListeners = new Set<(text: string) => void>();
  let disposed = false;

  const banner = `not running under Wails — this is a local echo, not a real shell${options.cwd ? ` (cwd: ${options.cwd})` : ""}\r\n`;
  queueMicrotask(() => { if (!disposed) dataListeners.forEach(listener => listener(banner)); });

  return {
    id,
    write: (data: string) => {
      if (disposed) return;
      // Echo typed input; turn a bare CR into CRLF so lines advance like a real tty.
      const echoed = data.replace(/\r(?!\n)/g, "\r\n");
      dataListeners.forEach(listener => listener(echoed));
    },
    resize: () => {},
    close: () => { disposed = true; },
    onData: listener => {
      dataListeners.add(listener);
      return () => dataListeners.delete(listener);
    },
    onExit: () => () => {},
    dispose: () => { disposed = true; dataListeners.clear(); },
  };
}
