// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BrowserService opens URLs in dedicated, trackable webview windows so the
 * frontend's "open in in-app browser" action has somewhere to go.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Close closes the named in-app browser window.
 */
export function Close(name: string): $CancellablePromise<void> {
    return $Call.ByID(2918748503, name);
}

/**
 * List returns every currently tracked in-app browser window.
 */
export function List(): $CancellablePromise<$models.BrowserWindow[]> {
    return $Call.ByID(946478789).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Open creates a new in-app browser window loading url and returns the
 * window's name.
 */
export function Open(rawURL: string): $CancellablePromise<string> {
    return $Call.ByID(1368667045, rawURL);
}

// Private type creation functions
const $$createType0 = $models.BrowserWindow.createFrom;
const $$createType1 = $Create.Array($$createType0);
