// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PtyDataEvent is emitted on "pty:data" as bytes are read from a session.
 * Data is base64 of the raw bytes read from the pty (binary safe).
 */
export interface PtyDataEvent {
    "Id": string;
    "Data": string;
}

/**
 * PtyExitEvent is emitted on "pty:exit" once a session's process exits.
 */
export interface PtyExitEvent {
    "Id": string;
    "Code": number;
}

/**
 * PtyInfo describes a live (or recently exited) pty session.
 */
export interface PtyInfo {
    "Id": string;
    "Cwd": string;
    "Command": string;
    "Pid": number;
    "Running": boolean;
}

/**
 * PtyOptions configures a new pty session.
 */
export interface PtyOptions {
    "Cwd": string;
    "Cols": number;
    "Rows": number;
    "Command": string;
}

/**
 * SidecarStatus reports the state of the @portfolio/api sidecar process.
 */
export interface SidecarStatus {
    "Url": string;
    "Running": boolean;
    "Pid": number;
    "Error": string;
}
