// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * BrowserWindow describes an open in-app browser window.
 */
export class BrowserWindow {
    "Name": string;
    "Url": string;
    "Title": string;

    /** Creates a new BrowserWindow instance. */
    constructor($$source: Partial<BrowserWindow> = {}) {
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Url" in $$source)) {
            this["Url"] = "";
        }
        if (!("Title" in $$source)) {
            this["Title"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BrowserWindow instance from a string or object.
     */
    static createFrom($$source: any = {}): BrowserWindow {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BrowserWindow($$parsedSource as Partial<BrowserWindow>);
    }
}

/**
 * PtyDataEvent is emitted on "pty:data" as bytes are read from a session.
 * Data is base64 of the raw bytes read from the pty (binary safe).
 */
export class PtyDataEvent {
    "Id": string;
    "Data": string;

    /** Creates a new PtyDataEvent instance. */
    constructor($$source: Partial<PtyDataEvent> = {}) {
        if (!("Id" in $$source)) {
            this["Id"] = "";
        }
        if (!("Data" in $$source)) {
            this["Data"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PtyDataEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): PtyDataEvent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PtyDataEvent($$parsedSource as Partial<PtyDataEvent>);
    }
}

/**
 * PtyExitEvent is emitted on "pty:exit" once a session's process exits.
 */
export class PtyExitEvent {
    "Id": string;
    "Code": number;

    /** Creates a new PtyExitEvent instance. */
    constructor($$source: Partial<PtyExitEvent> = {}) {
        if (!("Id" in $$source)) {
            this["Id"] = "";
        }
        if (!("Code" in $$source)) {
            this["Code"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PtyExitEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): PtyExitEvent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PtyExitEvent($$parsedSource as Partial<PtyExitEvent>);
    }
}

/**
 * PtyInfo describes a live (or recently exited) pty session.
 */
export class PtyInfo {
    "Id": string;
    "Cwd": string;
    "Command": string;
    "Pid": number;
    "Running": boolean;

    /** Creates a new PtyInfo instance. */
    constructor($$source: Partial<PtyInfo> = {}) {
        if (!("Id" in $$source)) {
            this["Id"] = "";
        }
        if (!("Cwd" in $$source)) {
            this["Cwd"] = "";
        }
        if (!("Command" in $$source)) {
            this["Command"] = "";
        }
        if (!("Pid" in $$source)) {
            this["Pid"] = 0;
        }
        if (!("Running" in $$source)) {
            this["Running"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PtyInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): PtyInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PtyInfo($$parsedSource as Partial<PtyInfo>);
    }
}

/**
 * PtyOptions configures a new pty session.
 */
export class PtyOptions {
    "Cwd": string;
    "Cols": number;
    "Rows": number;
    "Command": string;

    /** Creates a new PtyOptions instance. */
    constructor($$source: Partial<PtyOptions> = {}) {
        if (!("Cwd" in $$source)) {
            this["Cwd"] = "";
        }
        if (!("Cols" in $$source)) {
            this["Cols"] = 0;
        }
        if (!("Rows" in $$source)) {
            this["Rows"] = 0;
        }
        if (!("Command" in $$source)) {
            this["Command"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PtyOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): PtyOptions {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PtyOptions($$parsedSource as Partial<PtyOptions>);
    }
}

/**
 * SidecarStatus reports the state of the @portfolio/api sidecar process.
 */
export class SidecarStatus {
    "Url": string;
    "Running": boolean;
    "Pid": number;
    "Error": string;

    /** Creates a new SidecarStatus instance. */
    constructor($$source: Partial<SidecarStatus> = {}) {
        if (!("Url" in $$source)) {
            this["Url"] = "";
        }
        if (!("Running" in $$source)) {
            this["Running"] = false;
        }
        if (!("Pid" in $$source)) {
            this["Pid"] = 0;
        }
        if (!("Error" in $$source)) {
            this["Error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SidecarStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): SidecarStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SidecarStatus($$parsedSource as Partial<SidecarStatus>);
    }
}
