// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * NativeService wraps macOS `open`/`osascript` integrations and clipboard access.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * CopyText copies text to the system clipboard, via the Wails clipboard API
 * with a pbcopy fallback.
 */
export function CopyText(text: string): $CancellablePromise<void> {
    return $Call.ByID(4191864988, text);
}

/**
 * Home returns $HOME.
 */
export function Home(): $CancellablePromise<string> {
    return $Call.ByID(3272976761);
}

/**
 * Notify shows a macOS notification via osascript.
 */
export function Notify(title: string, body: string): $CancellablePromise<void> {
    return $Call.ByID(1657499619, title, body);
}

/**
 * OpenPath opens path with its default application.
 */
export function OpenPath(path: string): $CancellablePromise<void> {
    return $Call.ByID(1398118909, path);
}

/**
 * OpenUrl opens url in the system default browser.
 */
export function OpenUrl(url: string): $CancellablePromise<void> {
    return $Call.ByID(684754023, url);
}

/**
 * OpenWith opens path with the named application.
 */
export function OpenWith(path: string, app: string): $CancellablePromise<void> {
    return $Call.ByID(25271730, path, app);
}

/**
 * PickDirectory shows a native directory picker. start "" defaults to
 * $HOME; title "" defaults to "Choose a directory". Cancel returns "" and a
 * nil error.
 */
export function PickDirectory(title: string, start: string): $CancellablePromise<string> {
    return $Call.ByID(1129700750, title, start);
}

/**
 * PickFile shows a native file picker. start "" defaults to $HOME; title ""
 * defaults to "Choose a file". Cancel returns "" and a nil error.
 */
export function PickFile(title: string, start: string): $CancellablePromise<string> {
    return $Call.ByID(1673420489, title, start);
}

/**
 * Reveal shows path in Finder, highlighting it.
 */
export function Reveal(path: string): $CancellablePromise<void> {
    return $Call.ByID(2264880907, path);
}
