// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PtyService manages pty-backed shell sessions for the in-app terminal.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Close kills the session's process group and releases its pty.
 */
export function Close(id: string): $CancellablePromise<void> {
    return $Call.ByID(161784082, id);
}

/**
 * Create starts a new pty session and returns its id. Command "" starts a
 * login shell ($SHELL -l); otherwise the command runs via $SHELL -l -c.
 */
export function Create(opts: $models.PtyOptions): $CancellablePromise<string> {
    return $Call.ByID(3557416242, opts);
}

/**
 * List returns info for every known session.
 */
export function List(): $CancellablePromise<$models.PtyInfo[] | null> {
    return $Call.ByID(1978130210);
}

/**
 * Resize changes the pty's terminal size.
 */
export function Resize(id: string, cols: number, rows: number): $CancellablePromise<void> {
    return $Call.ByID(1169112074, id, cols, rows);
}

/**
 * Write sends raw text typed by the user to the session's pty.
 */
export function Write(id: string, data: string): $CancellablePromise<void> {
    return $Call.ByID(1502773937, id, data);
}
