// Wrappers over the Go bindings (frontend/bindings/portfolio-desktop/*.ts) that fall back to
// window.open / navigator.clipboard / console.warn when running outside the Wails webview
// (e.g. `bun run dev` in a normal browser), so the app is usable before the Go part lands and
// while developing in a browser tab.

import { isWails as inWails } from "./lib/wails.ts";

async function nativeService() {
  try {
    // @ts-ignore — generated by `wails3 generate bindings`; may not exist at typecheck/build time.
    return await import("../bindings/portfolio-desktop/nativeservice.ts");
  } catch {
    return null;
  }
}

async function browserService() {
  try {
    // @ts-ignore — generated by `wails3 generate bindings`; may not exist at typecheck/build time.
    return await import("../bindings/portfolio-desktop/browserservice.ts");
  } catch {
    return null;
  }
}

export async function openInApp(url: string): Promise<void> {
  if (inWails()) {
    const service = await browserService();
    // The generated module exports Open/List/Close directly (no namespace, no default), like nativeservice.ts.
    const impl = (service as any)?.BrowserService ?? (service as any)?.default ?? service;
    if (impl?.Open) {
      await impl.Open(url);
      return;
    }
  }
  window.open(url, "_blank", "noopener,noreferrer");
}

export async function openSystem(url: string): Promise<void> {
  if (inWails()) {
    const service = await nativeService();
    const impl = (service as any)?.NativeService ?? (service as any)?.default ?? service;
    if (impl?.OpenUrl) {
      await impl.OpenUrl(url);
      return;
    }
  }
  window.open(url, "_blank", "noopener,noreferrer");
}

export async function copyText(text: string): Promise<void> {
  if (inWails()) {
    const service = await nativeService();
    const impl = (service as any)?.NativeService ?? (service as any)?.default ?? service;
    if (impl?.CopyText) {
      await impl.CopyText(text);
      return;
    }
  }
  try {
    await navigator.clipboard.writeText(text);
  } catch (error) {
    console.warn("copyText: clipboard API unavailable", error);
  }
}

export async function reveal(path: string): Promise<void> {
  if (inWails()) {
    const service = await nativeService();
    const impl = (service as any)?.NativeService ?? (service as any)?.default ?? service;
    if (impl?.Reveal) {
      await impl.Reveal(path);
      return;
    }
  }
  console.warn(`reveal: not running in the desktop app, cannot reveal ${path}`);
}

export async function openPath(path: string): Promise<void> {
  if (inWails()) {
    const service = await nativeService();
    const impl = (service as any)?.NativeService ?? (service as any)?.default ?? service;
    if (impl?.OpenPath) {
      await impl.OpenPath(path);
      return;
    }
  }
  console.warn(`openPath: not running in the desktop app, cannot open ${path}`);
}

export async function openWith(path: string, app: string): Promise<void> {
  if (inWails()) {
    const service = await nativeService();
    const impl = (service as any)?.NativeService ?? (service as any)?.default ?? service;
    if (impl?.OpenWith) {
      await impl.OpenWith(path, app);
      return;
    }
  }
  console.warn(`openWith: not running in the desktop app, cannot open ${path} with ${app}`);
}

export async function notify(title: string, body: string): Promise<void> {
  if (inWails()) {
    const service = await nativeService();
    const impl = (service as any)?.NativeService ?? (service as any)?.default ?? service;
    if (impl?.Notify) {
      await impl.Notify(title, body);
      return;
    }
  }
  if (typeof Notification !== "undefined") {
    try {
      if (Notification.permission === "granted") {
        new Notification(title, { body });
        return;
      }
      if (Notification.permission !== "denied") {
        const permission = await Notification.requestPermission();
        if (permission === "granted") {
          new Notification(title, { body });
          return;
        }
      }
    } catch (error) {
      console.warn("notify: Notification API failed", error);
    }
  }
  console.warn(`notify: ${title} — ${body}`);
}

/** $HOME, used as the default start directory for pickers. "" outside Wails. */
export async function home(): Promise<string> {
  if (inWails()) {
    const service = await nativeService();
    const impl = (service as any)?.NativeService ?? (service as any)?.default ?? service;
    if (impl?.Home) {
      return await impl.Home();
    }
  }
  return "";
}

/** Native "choose a directory" dialog. Returns "" when cancelled or unavailable (not in Wails). */
export async function pickDirectory(title: string, start?: string): Promise<string> {
  if (inWails()) {
    const service = await nativeService();
    const impl = (service as any)?.NativeService ?? (service as any)?.default ?? service;
    if (impl?.PickDirectory) {
      return await impl.PickDirectory(title, start ?? "");
    }
  }
  return "";
}

/** Native "choose a file" dialog. Returns "" when cancelled or unavailable (not in Wails). */
export async function pickFile(title: string, start?: string): Promise<string> {
  if (inWails()) {
    const service = await nativeService();
    const impl = (service as any)?.NativeService ?? (service as any)?.default ?? service;
    if (impl?.PickFile) {
      return await impl.PickFile(title, start ?? "");
    }
  }
  return "";
}
