/// <reference types="vite/client" />

interface ImportMetaEnv {
  readonly VITE_PORTFOLIO_API?: string;
}

interface ImportMeta {
  readonly env: ImportMetaEnv;
}

// The Go bindings under ../bindings/portfolio-desktop/*.ts are generated by
// `wails3 generate bindings` and may not exist yet at typecheck time (the "go" part of the
// contract owns them). src/native.ts imports them dynamically with `// @ts-ignore` on the
// import line so a missing module never breaks `tsc --noEmit` or the build.

// Needed by src/terminal/ghostty (vendored from t3code): the wasm binaries and the
// symbols font are loaded via Vite's `?url` asset-URL imports, which vite/client's
// wildcard asset types don't cover for these extensions.
declare module "*.wasm?url" {
  const url: string;
  export default url;
}

declare module "*.wasm?url&no-inline" {
  const url: string;
  export default url;
}

declare module "*.woff2?url" {
  const url: string;
  export default url;
}
